name: valid_sudoku
description: Author - Levon Khorasandzhian (@lkhorasandzhian)

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Helpful library for data providing.
  provider: ^6.0.2

  # Special library for URL opening.
  url_launcher: ^6.1.7

  # Special library for uploading sudoku draft files.
  file_picker: ^4.0.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/sudoku_icon_101x101.png"
  web:
    generate: true
    image_path: "assets/icon/sudoku_icon_101x101.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/sudoku_icon_101x101.png"
    icon_size: 101 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/sudoku_icon_101x101.png"

flutter:
  uses-material-design: true
